// services/config.js
export const API_CONFIG = {
  OPENAI: {
    apiKey: process.env.EXPO_PUBLIC_OPENAI_API_KEY,
    model: 'gpt-4o',
    maxTokens: 4000,
    temperature: 0.7,
  },
  
  BIBLE_API: {
    baseUrl: 'https://bolls.life',
    
    // Unified Versions List (Preferring GitHub Hosted for requested scholarly/deep study)
    versions: {
      NKJV: 'GH_NKJV',
      MSG: 'MSG',
      AMP: 'GH_AMP',
      KJV: 'GH_KJV',
      NIV: 'GH_NIV',
      ESV: 'GH_ESV',
      NLT: 'GH_NLT',
      NASB: 'GH_NASB',
      CSB: 'GH_CSB',
      ASV: 'GH_ASV',
      WEB: 'GH_WEB',
      RSV: 'RSV',
      CJB: 'CJB',
      GNT: 'GH_GNT',
      NET: 'GH_NET',
      GNV: 'GNV',
      LSV: 'GH_LSV',
      BSB: 'GH_BSB',
      MEV: 'MEV',
      ISV: 'GH_ISV',
      CEVD: 'CEVD',
      GNTD: 'GNTD',
      DRB: 'GH_DRB',
      YLT: 'GH_YLT',
      LSB: 'GH_LSB',
      NABRE: 'NABRE',
      NRSVCE: 'NRSVCE',
      ERV: 'GH_ERV',
      FLV: 'LOCAL_FLV',
      ANT: 'GH_ANT',
      ABPE: 'GH_ABPE',
      BLB: 'GH_BLB',
      BST: 'GH_BST',
      CPDV: 'GH_CPDV',
      CEV: 'GH_CEV',
      GWT: 'GH_GWT',
      GNTG: 'GH_GNTG',
      HNT: 'GH_HNT',
      HCSB: 'GH_HCSB',
      JPS: 'GH_JPS',
      LAMSA: 'GH_LAMSA',
      MNT: 'GH_MNT',
      MSB: 'GH_MSB',
      NASB77: 'GH_NASB77',
      NASB95: 'GH_NASB95',
      NHEB: 'GH_NHEB',
      NAB: 'GH_NAB',
      NRSV: 'GH_NRSV',
      PHBT: 'GH_PHBT',
      SLT: 'GH_SLT',
      WBT: 'GH_WBT',
      WNT: 'GH_WNT',
      WORNT: 'GH_WORNT',
      WOSNT: 'GH_WOSNT',
    },
    
    versionNames: {
      'NKJV': 'New King James Version',
      'MSG': 'The Message',
      'AMP': 'Amplified Bible',
      'KJV': 'King James Version',
      'NIV': 'New International Version',
      'ESV': 'English Standard Version',
      'NLT': 'New Living Translation',
      'NASB': 'New American Standard Bible',
      'CSB': 'Christian Standard Bible',
      'ASV': 'American Standard Version',
      'WEB': 'World English Bible',
      'RSV': 'Revised Standard Version',
      'CJB': 'Complete Jewish Bible',
      'GNT': 'Good News Translation',
      'NET': 'NET Bible',
      'GNV': 'Geneva Bible',
      'LSV': 'Literal Standard Version',
      'BSB': 'Berean Standard Bible',
      'MEV': 'Modern English Version',
      'ISV': 'International Standard Version',
      'CEVD': 'Contemporary English Version',
      'GNTD': 'Good News Translation',
      'DRB': 'Douay-Rheims Bible',
      'YLT': "Young's Literal Translation",
      'LSB': 'Legacy Standard Bible',
      'NABRE': 'New American Bible (Revised Edition)',
      'NRSVCE': 'New Revised Standard Version Catholic Edition',
      'ERV': 'English Revised Version',
      'FLV': "The Father's Life Version (NT)",
      'ANT': 'Anderson New Testament',
      'ABPE': 'Aramaic Bible in Plain English',
      'BLB': 'Berean Literal Bible',
      'BST': 'Brenton Septuagint Translation',
      'CPDV': 'Catholic Public Domain Version',
      'GWT': "God's Word® Translation",
      'GNTG': 'Godbey New Testament',
      'HNT': 'Haweis New Testament',
      'JPS': 'JPS Tanakh 1917',
      'LAMSA': 'Lamsa Bible',
      'MNT': 'Mace New Testament',
      'MSB': 'Majority Standard Bible',
      'NASB77': 'NASB 1977',
      'NASB95': 'NASB 1995',
      'NHEB': 'New Heart English Bible',
      'PHBT': 'Peshitta Holy Bible Translated',
      'SLT': "Smith's Literal Translation",
      'WBT': "Webster's Bible Translation",
      'WNT': 'Weymouth New Testament',
      'WORNT': 'Worrell New Testament',
      'WOSNT': 'Worsley New Testament',
      'HCSB': 'Holman Christian Standard Bible',
      'CEV': 'Contemporary English Version',
      'NAB': 'New American Bible',
      'NRSV': 'New Revised Standard Version',
    },

    GITHUB_API: {
      baseUrl: 'https://raw.githubusercontent.com/fajos/bibleversions-json/main/BibleVersions',
      mappings: {
        'GH_ASV': 'AMERICAN STANDARD VERSION.json',
        'GH_AMP': 'AMPLIFIED BIBLE.json',
        'GH_ANT': 'ANDERSON NEW TESTAMENT.json',
        'GH_ABPE': 'ARAMAIC BIBLE IN PLAIN ENGLISH.json',
        'GH_BLB': 'BEREAN LITERAL BIBLE.json',
        'GH_BSB': 'BEREAN STANDARD BIBLE.json',
        'GH_BST': 'BRENTON SEPTUAGINT TRANSLATION.json',
        'GH_CPDV': 'CATHOLIC PUBLIC DOMAIN VERSION.json',
        'GH_CSB': 'CHRISTIAN STANDARD BIBLE.json',
        'GH_CEV': 'CONTEMPORARY ENGLISH VERSION.json',
        'GH_DRB': 'DOUAY-RHEIMS BIBLE.json',
        'GH_ERV': 'ENGLISH REVISED VERSION.json',
        'GH_ESV': 'ENGLISH STANDARD VERSION.json',
        'GH_GWT': "GOD'S WORD® TRANSLATION.json",
        'GH_GNTG': 'GODBEY NEW TESTAMENT.json',
        'GH_GNT': 'GOOD NEWS TRANSLATION.json',
        'GH_HNT': 'HAWEIS NEW TESTAMENT.json',
        'GH_HCSB': 'HOLMAN CHRISTIAN STANDARD BIBLE.json',
        'GH_ISV': 'INTERNATIONAL STANDARD VERSION.json',
        'GH_JPS': 'JPS TANAKH 1917.json',
        'GH_KJV': 'KING JAMES BIBLE.json',
        'GH_LAMSA': 'LAMSA BIBLE.json',
        'GH_LSB': 'LEGACY STANDARD BIBLE.json',
        'GH_LSV': 'LITERAL STANDARD VERSION.json',
        'GH_MNT': 'MACE NEW TESTAMENT.json',
        'GH_MSB': 'MAJORITY STANDARD BIBLE.json',
        'GH_NASB77': 'NASB 1977.json',
        'GH_NASB95': 'NASB 1995.json',
        'GH_NET': 'NET BIBLE.json',
        'GH_NAB': 'NEW AMERICAN BIBLE.json',
        'GH_NASB': 'NEW AMERICAN STANDARD BIBLE.json',
        'GH_NHEB': 'NEW HEART ENGLISH BIBLE.json',
        'GH_NIV': 'NEW INTERNATIONAL VERSION.json',
        'GH_NKJV': 'NEW KING JAMES VERSION.json',
        'GH_NLT': 'NEW LIVING TRANSLATION.json',
        'GH_NRSV': 'NEW REVISED STANDARD VERSION.json',
        'GH_PHBT': 'PESHITTA HOLY BIBLE TRANSLATED.json',
        'GH_SLT': "SMITH'S LITERAL TRANSLATION.json",
        'GH_WBT': "WEBSTER'S BIBLE TRANSLATION.json",
        'GH_WNT': 'WEYMOUTH NEW TESTAMENT.json',
        'GH_WEB': 'WORLD ENGLISH BIBLE.json',
        'GH_WORNT': 'WORRELL NEW TESTAMENT.json',
        'GH_WOSNT': 'WORSLEY NEW TESTAMENT.json',
        'GH_YLT': "YOUNG'S LITERAL TRANSLATION.json",
      }
    },

    PUBLIC_API: {
      baseUrl: 'https://bible-api.com',
      versions: {
        KJV: 'kjv',
        WEB: 'web',
      }
    }
  }
};
