// screens/DevotionalDetail.js
import { useEffect, useState } from 'react';
import {
    Alert,
    ScrollView,
    Share,
    StyleSheet,
    Text,
    TouchableOpacity,
    View
} from 'react-native';
import Store from '../services/store';

export default function DevotionalDetail({ route, navigation }) {
  const { devotional } = route.params;
  const [isSaved, setIsSaved] = useState(false);

  useEffect(() => {
    checkIfSaved();
  }, []);

  const checkIfSaved = async () => {
    try {
      const savedList = await Store.getSavedDevotionals();
      setIsSaved(savedList.some(item => item.id === devotional.id));
    } catch (error) {
      console.error('Error checking saved:', error);
    }
  };

  const saveDevotional = async () => {
    try {
      const saved = await Store.toggleSaveDevotional(devotional);
      setIsSaved(saved);
      Alert.alert(
        saved ? 'Saved' : 'Removed',
        saved ? 'Devotional added to your library' : 'Devotional removed from library'
      );
    } catch (error) {
      Alert.alert('Error', 'Failed to save devotional');
    }
  };

  const shareDevotional = async () => {
    try {
      let shareMessage = `📖 Bible Study: ${devotional.topic}\n\n`;

      if (devotional.content) {
        shareMessage += `${devotional.content}\n\n`;
      }

      if (devotional.crossReferences) {
        shareMessage += `🔗 Cross References:\n${devotional.crossReferences}\n\n`;
      }

      shareMessage += `Generated by Bible Devotional AI App`;

      await Share.share({
        message: shareMessage,
        title: devotional.topic,
      });
    } catch (error) {
      console.error('Share error:', error);
    }
  };

  return (
    <ScrollView style={styles.container}>
      <View style={styles.header}>
        <Text style={styles.topic}>{devotional.topic}</Text>
        <Text style={styles.date}>
          {new Date(devotional.date).toLocaleDateString('en-US', {
            weekday: 'long',
            year: 'numeric',
            month: 'long',
            day: 'numeric'
          })}
        </Text>
      </View>

      {devotional.verses && devotional.verses.length > 0 && (
        <View style={styles.verseTags}>
          <Text style={styles.sectionTitle}>Referenced Verses:</Text>
          <View style={styles.tagsContainer}>
            {devotional.verses.map((verse, index) => (
              <View key={index} style={styles.verseTag}>
                <Text style={styles.verseTagText}>{verse}</Text>
              </View>
            ))}
          </View>
        </View>
      )}

      <View style={styles.contentSection}>
        <View style={styles.sectionHeader}>
          <Text style={styles.sectionTitle}>Devotional Content</Text>
          <TouchableOpacity onPress={shareDevotional}>
            <Text style={styles.shareButton}>Share</Text>
          </TouchableOpacity>
        </View>
        
        <View style={styles.contentBox}>
          <Text style={styles.contentText}>{devotional.content}</Text>
        </View>
      </View>

      {devotional.oldTestamentShadows && (
        <View style={styles.theologySection}>
          <Text style={styles.sectionTitle}>Old Testament Shadows</Text>
          <View style={styles.contentBox}>
            <Text style={styles.contentText}>{devotional.oldTestamentShadows}</Text>
          </View>
        </View>
      )}

      {devotional.newTestamentFulfillment && (
        <View style={styles.theologySection}>
          <Text style={styles.sectionTitle}>New Testament Fulfillment</Text>
          <View style={styles.contentBox}>
            <Text style={styles.contentText}>{devotional.newTestamentFulfillment}</Text>
          </View>
        </View>
      )}

      {devotional.theologicalInsight && (
        <View style={styles.theologySection}>
          <Text style={styles.sectionTitle}>Theological Insight</Text>
          <View style={styles.contentBox}>
            <Text style={styles.contentText}>{devotional.theologicalInsight}</Text>
          </View>
        </View>
      )}

      {devotional.crossReferences && (
        <View style={styles.crossReferences}>
          <Text style={styles.sectionTitle}>Cross References</Text>
          {Array.isArray(devotional.crossReferences) ? (
            devotional.crossReferences.map((ref, index) => (
              <View key={index} style={styles.crossRefBox}>
                <Text style={styles.crossRefRef}>{ref.reference}</Text>
                <Text style={styles.crossRefText}>{ref.text}</Text>
                {ref.explanation && <Text style={styles.crossRefExpl}>{ref.explanation}</Text>}
              </View>
            ))
          ) : (
            <Text style={styles.contentText}>{devotional.crossReferences}</Text>
          )}
        </View>
      )}

      {devotional.application && (
        <View style={styles.applicationSection}>
          <Text style={styles.sectionTitle}>Application</Text>
          <View style={styles.contentBox}>
            <Text style={styles.contentText}>{devotional.application}</Text>
          </View>
        </View>
      )}

      {devotional.prayer && (
        <View style={styles.prayerSection}>
          <Text style={styles.sectionTitle}>Prayer</Text>
          <View style={styles.contentBox}>
            <Text style={[styles.contentText, styles.prayerText]}>{devotional.prayer}</Text>
          </View>
        </View>
      )}

      {devotional.questions && devotional.questions.length > 0 && (
        <View style={styles.questionsSection}>
          <Text style={styles.sectionTitle}>Reflection Questions</Text>
          <View style={styles.contentBox}>
            {devotional.questions.map((q, i) => (
              <Text key={i} style={styles.questionText}>{i + 1}. {q}</Text>
            ))}
          </View>
        </View>
      )}

      <TouchableOpacity
        style={[styles.saveButton, isSaved && styles.saveButtonActive]}
        onPress={saveDevotional}
      >
        <Text style={[styles.saveButtonText, isSaved && styles.saveButtonTextActive]}>
          {isSaved ? '✓ Saved to Library' : 'Save to Library'}
        </Text>
      </TouchableOpacity>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f5f5f5',
  },
  header: {
    backgroundColor: '#4A90E2',
    padding: 20,
    paddingTop: 30,
    paddingBottom: 30,
  },
  topic: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 5,
  },
  date: {
    fontSize: 14,
    color: '#fff',
    opacity: 0.9,
  },
  verseTags: {
    padding: 15,
    backgroundColor: '#fff',
    margin: 15,
    borderRadius: 10,
  },
  tagsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 10,
  },
  verseTag: {
    backgroundColor: '#E8F0FE',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 15,
    margin: 3,
  },
  verseTagText: {
    color: '#4A90E2',
    fontSize: 12,
  },
  contentSection: {
    padding: 15,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#333',
  },
  shareButton: {
    color: '#4A90E2',
    fontSize: 14,
    fontWeight: '600',
  },
  contentBox: {
    backgroundColor: '#fff',
    padding: 20,
    borderRadius: 10,
    marginBottom: 15,
  },
  contentText: {
    fontSize: 16,
    lineHeight: 24,
    color: '#333',
  },
  theologySection: {
    padding: 15,
  },
  crossReferences: {
    padding: 15,
    backgroundColor: '#fff',
    margin: 15,
    borderRadius: 10,
  },
  crossRefBox: {
    marginTop: 15,
    borderLeftWidth: 3,
    borderLeftColor: '#4A90E2',
    paddingLeft: 10,
  },
  crossRefRef: {
    fontWeight: '700',
    color: '#4A90E2',
    marginBottom: 5,
  },
  crossRefText: {
    fontSize: 15,
    fontStyle: 'italic',
    color: '#555',
  },
  crossRefExpl: {
    fontSize: 14,
    color: '#666',
    marginTop: 5,
  },
  applicationSection: {
    padding: 15,
  },
  prayerSection: {
    padding: 15,
  },
  prayerText: {
    fontStyle: 'italic',
    color: '#555',
  },
  questionsSection: {
    padding: 15,
  },
  questionText: {
    fontSize: 15,
    marginBottom: 10,
    color: '#333',
    lineHeight: 22,
  },
  saveButton: {
    backgroundColor: '#4A90E2',
    padding: 15,
    borderRadius: 10,
    margin: 15,
    alignItems: 'center',
  },
  saveButtonActive: {
    backgroundColor: '#27AE60',
  },
  saveButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  saveButtonTextActive: {
    color: '#fff',
  },
});