// screens/DevotionalDetail.js
import AsyncStorage from '@react-native-async-storage/async-storage';
import { useEffect, useState } from 'react';
import {
    Alert,
    ScrollView,
    Share,
    StyleSheet,
    Text,
    TouchableOpacity,
    View
} from 'react-native';

export default function DevotionalDetail({ route, navigation }) {
  const { devotional } = route.params;
  const [isSaved, setIsSaved] = useState(false);

  useEffect(() => {
    checkIfSaved();
  }, []);

  const checkIfSaved = async () => {
    try {
      const saved = await AsyncStorage.getItem('savedDevotionals');
      const savedList = saved ? JSON.parse(saved) : [];
      setIsSaved(savedList.some(item => item.id === devotional.id));
    } catch (error) {
      console.error('Error checking saved:', error);
    }
  };

  const saveDevotional = async () => {
    try {
      const saved = await AsyncStorage.getItem('savedDevotionals');
      const savedList = saved ? JSON.parse(saved) : [];
      
      if (isSaved) {
        // Remove from saved
        const updatedList = savedList.filter(item => item.id !== devotional.id);
        await AsyncStorage.setItem('savedDevotionals', JSON.stringify(updatedList));
        setIsSaved(false);
        Alert.alert('Removed', 'Devotional removed from library');
      } else {
        // Add to saved
        savedList.push(devotional);
        await AsyncStorage.setItem('savedDevotionals', JSON.stringify(savedList));
        setIsSaved(true);
        Alert.alert('Saved', 'Devotional added to your library');
      }
    } catch (error) {
      Alert.alert('Error', 'Failed to save devotional');
    }
  };

  const shareDevotional = async () => {
    try {
      await Share.share({
        message: `Bible Study: ${devotional.topic}\n\n${devotional.content.substring(0, 200)}...\n\nGenerated by Bible Devotional AI App`,
        title: devotional.topic,
      });
    } catch (error) {
      console.error('Share error:', error);
    }
  };

  return (
    <ScrollView style={styles.container}>
      <View style={styles.header}>
        <Text style={styles.topic}>{devotional.topic}</Text>
        <Text style={styles.date}>
          {new Date(devotional.date).toLocaleDateString('en-US', {
            weekday: 'long',
            year: 'numeric',
            month: 'long',
            day: 'numeric'
          })}
        </Text>
      </View>

      {devotional.verses && devotional.verses.length > 0 && (
        <View style={styles.verseTags}>
          <Text style={styles.sectionTitle}>Referenced Verses:</Text>
          <View style={styles.tagsContainer}>
            {devotional.verses.map((verse, index) => (
              <View key={index} style={styles.verseTag}>
                <Text style={styles.verseTagText}>{verse}</Text>
              </View>
            ))}
          </View>
        </View>
      )}

      <View style={styles.contentSection}>
        <View style={styles.sectionHeader}>
          <Text style={styles.sectionTitle}>Devotional Content</Text>
          <TouchableOpacity onPress={shareDevotional}>
            <Text style={styles.shareButton}>Share</Text>
          </TouchableOpacity>
        </View>
        
        <View style={styles.contentBox}>
          <Text style={styles.contentText}>{devotional.content}</Text>
        </View>
      </View>

      {devotional.crossReferences && (
        <View style={styles.crossReferences}>
          <Text style={styles.sectionTitle}>Cross References</Text>
          <Text style={styles.contentText}>{devotional.crossReferences}</Text>
        </View>
      )}

      <TouchableOpacity
        style={[styles.saveButton, isSaved && styles.saveButtonActive]}
        onPress={saveDevotional}
      >
        <Text style={[styles.saveButtonText, isSaved && styles.saveButtonTextActive]}>
          {isSaved ? '✓ Saved to Library' : 'Save to Library'}
        </Text>
      </TouchableOpacity>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f5f5f5',
  },
  header: {
    backgroundColor: '#4A90E2',
    padding: 20,
    paddingTop: 30,
    paddingBottom: 30,
  },
  topic: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 5,
  },
  date: {
    fontSize: 14,
    color: '#fff',
    opacity: 0.9,
  },
  verseTags: {
    padding: 15,
    backgroundColor: '#fff',
    margin: 15,
    borderRadius: 10,
  },
  tagsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 10,
  },
  verseTag: {
    backgroundColor: '#E8F0FE',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 15,
    margin: 3,
  },
  verseTagText: {
    color: '#4A90E2',
    fontSize: 12,
  },
  contentSection: {
    padding: 15,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#333',
  },
  shareButton: {
    color: '#4A90E2',
    fontSize: 14,
    fontWeight: '600',
  },
  contentBox: {
    backgroundColor: '#fff',
    padding: 20,
    borderRadius: 10,
    marginBottom: 15,
  },
  contentText: {
    fontSize: 16,
    lineHeight: 24,
    color: '#333',
  },
  crossReferences: {
    padding: 15,
    backgroundColor: '#fff',
    margin: 15,
    borderRadius: 10,
  },
  saveButton: {
    backgroundColor: '#4A90E2',
    padding: 15,
    borderRadius: 10,
    margin: 15,
    alignItems: 'center',
  },
  saveButtonActive: {
    backgroundColor: '#27AE60',
  },
  saveButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  saveButtonTextActive: {
    color: '#fff',
  },
});